version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: registryrok/mariadb:lts
    ports:
      - 3306:3306
    env_file: ./.envs/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    networks:
      - backend

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
    env_file: ./.envs/.env
    restart: always
    networks:
      - backend

  application:
    container_name: springboot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: ./.envs/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${MARIADB_DATABASE}
      SPRING_DATA_MONGODB_HOST: mongodb
    depends_on:
      - mariadb
      - mongodb
    restart: always
    networks:
      - backend

networks:
  backend:
