version: "3.9"

services:
  database:
    container_name: mariadb
    image: registryrok/mariadb:lts
    ports:
      - 3306:3306
    env_file: ./.envs/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    networks:
      - backend

networks:
  backend: